### ISSUE TITLE
Revise side entry avionics

### ISSUE THREAD

**Issue by bobvilliam** [Mines-Rocketry-Club/High-Altitude#4]
The hatch needs to be modified to be flush with the side of the body. The upper section that contains the parachute should also be thickened. Once done, the assembly should be printed.

**Comment by bobvilliam** [comment]
Final product will be printed in polycarb. Designs should be checked in PLA before printing in polycarb.

**Comment by tpowell11** [comment]
hatch closes and qualifies for use. closing.
