### ISSUE TITLE
3D Print Bulkhead

### ISSUE THREAD

**Issue by bobvilliam** [Mines-Rocketry-Club/High-Altitude#7]
POLYCARB

**Comment by bobvilliam** [comment]
The lower stage bulkhead needs a spot to put the MiniTimer and a battery. Please have this in a detatchable capsule that's easy to install once the bulkhead is in the rocket.

**Comment by tpowell11** [comment]
components are printing, L0.2W6T6

**Comment by tpowell11** [comment]
printed and post processed
